### ISSUE TITLE
RangeError: Wrong length!

### ISSUE THREAD

**Issue by starcrest** [truevault/truevault-react-js-sample-app#12]
I get the below error when running `node index.js` in the [tutorial](https://github.com/truevault/truevault-react-js-sample-app). I've tried fresh installs on both Mac OS X 10.15 and on Ubuntu 20.04, and gotten the same error on both.

```
/home/starcrest/truevault-react-js-sample-app/server/node_modules/truevault/build/index.js:2371
  if(numberLength != byteLength)throw RangeError(WRONG_LENGTH);
                                ^

RangeError: Wrong length!
    at validateArrayBufferArguments (/home/starcrest/truevault-react-js-sample-app/server/node_modules/truevault/build/index.js:2371:39)
    at new ArrayBuffer (/home/starcrest/truevault-react-js-sample-app/server/node_modules/truevault/build/index.js:2461:29)
    at zlib.js:330:28
    at NativeModule.compile (internal/bootstrap/loaders.js:364:7)
    at Function.NativeModule.require (internal/bootstrap/loaders.js:176:18)
    at Function.Module._load (internal/modules/cjs/loader.js:572:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/starcrest/truevault-react-js-sample-app/server/node_modules/node-fetch/index.js:12:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
```

**Comment by starcrest** [comment]
Still not working on Mac OS X 10.15.

But I did get it working in Ubuntu, by fixing some yarn installation errors I'd missed. Clean yarn install on Mac doesn't help.

**Comment by sathkur** [comment]
Was able to fixed this. As @starcrest mentioned above, fixing you packages intallation errors, this should work. I did 'npm audit fix' and worked for me.
